version: '3'
services:
  selenoid:
    restart: always
    network_mode: bridge
    image: aerokube/selenoid:1.11.3
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "C:/temp/selenoid/video:/opt/selenoid/video"
      - "C:/temp/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=C:/temp/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
        
  selenoid-ui:
    restart: always
    image: "aerokube/selenoid-ui:1.10.11"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8888:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]